# =======================================================
# Policy Summary Assistant
# =======================================================

import os
import pdfplumber
import argparse
import textwrap
import yagmail
from dotenv import load_dotenv
from fpdf import FPDF
from openai import AzureOpenAI

# Load Environment Variables
load_dotenv()

# -----------------------------
# Azure OpenAI Setup
# -----------------------------
client = AzureOpenAI(
    api_key=os.getenv("AZURE_OPENAI_API_KEY"),          # Using Azure OpenAI API key
    azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT"),  # Example: https://xxx.openai.azure.com/
    api_version="2024-02-01"
)
DEPLOYMENT = os.getenv("AZURE_OPENAI_DEPLOYMENT")       # Model deployment name

# -----------------------------
# Email Credentials
# -----------------------------
EMAIL_USER = os.getenv("EMAIL_USER")
EMAIL_PASSWORD = os.getenv("EMAIL_PASSWORD")
EMAIL_TO = os.getenv("NOTIFY_EMAIL_TO")

# -----------------------------
# Extract PDF text
# -----------------------------
def extract_text_from_pdf(pdf_path):
    text = ""
    with pdfplumber.open(pdf_path) as pdf:
        for page in pdf.pages:
            txt = page.extract_text()
            if txt:
                text += txt + "\n"
    return text.strip()

# -----------------------------
# Chunk text for RAG improvement
# -----------------------------
def chunk_text(text, chunk_size=2000):
    return [text[i:i+chunk_size] for i in range(0, len(text), chunk_size)]

# -----------------------------
# LLM call helper
# -----------------------------
def call_llm(prompt):
    response = client.chat.completions.create(
        model=DEPLOYMENT,
        messages=[{"role": "user", "content": prompt}]
    )
    return response.choices[0].message.content.strip()

# -----------------------------
# Generate JSON Structured Summary
# -----------------------------
def generate_structured_json(raw_text):
    prompt = f"""
    Convert this policy text into a STRICT JSON with these fields:
    {{
      "coverage": [],
      "exclusions": [],
      "limits": [],
      "eligibility": [],
      "waiting_periods": [],
      "disclaimers": []
    }}

    Policy Text:
    {raw_text[:6000]}

    Answer ONLY JSON:
    """
    return call_llm(prompt)

# -----------------------------
# Human English summary
# -----------------------------
def generate_english_summary(text, length=200):
    prompt = f"""
    Summarize the insurance policy in {length} words, plain English,
    include coverage, exclusions, limits, waiting periods, disclaimers.
    Text:
    {text}
    """
    return call_llm(prompt)

# -----------------------------
# Translate summary (Hindi / Marathi)
# -----------------------------
def translate_text(text, lang):
    prompt = f"Translate the following into {lang}:\n{text}"
    return call_llm(prompt)

# -----------------------------
# Export Summary to PDF
# -----------------------------
def save_pdf(summary, filename="policy_summary.pdf"):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=10)

    # Add UTF-8 compatible font
    pdf.set_font("Arial", size=11)

    for line in summary.split("\n"):
        try:
            pdf.multi_cell(0, 6, line.encode("latin-1", "replace").decode("latin-1"))
        except:
            # fallback convert unknown chars
            safe_line = line.encode("latin-1", "replace").decode("latin-1")
            pdf.multi_cell(0, 6, safe_line)

    pdf.output(filename, "F")
    print(f"[INFO] PDF saved → {filename}")
    return filename

# -----------------------------
# Send Summary via Email
# -----------------------------
def send_email_with_pdf(pdf_file):
    try:
        yag = yagmail.SMTP(EMAIL_USER, EMAIL_PASSWORD)

        email_body = f"""
Dear Sir/Madam,

Please find attached the Insurance Policy Summary Report generated by the Policy Summary Assistant.

This document includes:
• Structured JSON summary (coverage, exclusions, limits, eligibility)
• Plain-language English summary
• Translated summaries (if selected)

Should you need additional formatting or multiple policy reports, feel free to reply.

Best regards,
Policy Summary Assistant
"""

        yag.send(
            to=EMAIL_TO,
            subject="Insurance Policy Summary Report – Attached PDF",
            contents=email_body,
            attachments=[pdf_file]
        )

        print(f"[INFO] Email sent → {EMAIL_TO}")

    except Exception as e:
        print("[ERROR] Email Failed:", e)

# -----------------------------
# Interactive Menu UX
# -----------------------------
def interactive_mode():
    print("\n====================================================")
    print(" POLICY SUMMARY ASSISTANT – INTERACTIVE MODE")
    print("====================================================")
    print("Enter the path of your PDF file (Example: docs/HealthPolicy.pdf)")
    pdf_path = input("PDF File Path: ").strip()

    length_input = input("Summary Length (default = 200): ").strip()
    length = int(length_input) if length_input else 200

    print("\nChoose summary output language:")
    print("1. Marathi")
    print("2. Hindi")
    print("3. None (English Only)")

    lang_choice = input("Enter choice number (1/2/3): ").strip()

    if lang_choice == "1":
        lang = "marathi"
    elif lang_choice == "2":
        lang = "hindi"
    else:
        lang = "english"

    return pdf_path, length, lang

# -----------------------------
# MAIN
# -----------------------------
def main():
    parser = argparse.ArgumentParser(description="Policy Summary Generator (Azure OpenAI)")
    parser.add_argument("--pdf", required=False, help="Path to PDF file")
    parser.add_argument("--length", type=int, default=200, help="English summary length")
    parser.add_argument("--lang", required=False, default=None,
                        help="english / hindi / marathi / all")
    args = parser.parse_args()

    # If user did NOT provide --pdf → open interactive UX
    if not args.pdf:
        args.pdf, args.length, chosen_lang = interactive_mode()
        if args.lang is None:
            args.lang = chosen_lang

    print("\n[INFO] Reading PDF...")
    raw_text = extract_text_from_pdf(args.pdf)
    if not raw_text:
        print("[ERROR] No text extracted. Check PDF file path or upload a proper readable PDF.")
        return

    chunks = chunk_text(raw_text)
    text_for_summary = chunks[0]

    print("[INFO] Generating JSON structured summary...")
    json_summary = generate_structured_json(text_for_summary)
    print("\n=== STRUCTURED JSON SUMMARY ===\n")
    print(json_summary)

    print("\n[INFO] Generating English summary...")
    english_summary = generate_english_summary(text_for_summary, args.length)
    print("\n=== HUMAN SUMMARY (ENGLISH) ===\n")
    print(textwrap.fill(english_summary, width=100))

    # -------- LANGUAGE LOGIC ----------
    hindi = ""
    marathi = ""

    if args.lang.lower() in ["hindi", "all"]:
        print("\n[INFO] Translating (Hindi)...")
        hindi = translate_text(english_summary, "Hindi")
        print("\n=== HINDI SUMMARY ===\n")
        print(textwrap.fill(hindi, width=100))

    if args.lang.lower() in ["marathi", "all"]:
        print("\n[INFO] Translating (Marathi)...")
        marathi = translate_text(english_summary, "Marathi")
        print("\n=== MARATHI SUMMARY ===\n")
        print(textwrap.fill(marathi, width=100))

    # -------- PDF CONTENT BUILD ----------
    combined_pdf_text = f"""
    === POLICY SUMMARY (ENGLISH) ===
    {english_summary}

    === JSON SUMMARY ===
    {json_summary}
    """

    if hindi:
        combined_pdf_text += f"""

    === HINDI SUMMARY ===
    {hindi}
    """

    if marathi:
        combined_pdf_text += f"""

    === MARATHI SUMMARY ===
    {marathi}
    """

    # ====== Save PDF first so user can view ======
    pdf_name = save_pdf(combined_pdf_text)
    print(f"\n[INFO] PDF downloaded and saved → {pdf_name}")
    print("Please open the file to preview before choosing email delivery.")

    # ====== Ask user whether to send email ======
    choice = input("\nDo you want to send this PDF by email? (yes/no): ").strip().lower()

    if choice == "yes":
        custom_email = input(f"Enter recipient email (press Enter to use default {EMAIL_TO}): ").strip()
        send_to = custom_email if custom_email else EMAIL_TO

        email_body = f"""
Dear Sir/Madam,

Attached is the generated Insurance Policy Summary Report for your uploaded file.

This document includes:
• Structured JSON summary (coverage, exclusions, limits, eligibility)
• English plain language summary
• Hindi / Marathi translation (if enabled)

Please review and contact us if additional reports or formatting changes are required.

Regards,
Policy Summary Assistant
        """

        try:
            yag = yagmail.SMTP(EMAIL_USER, EMAIL_PASSWORD)
            yag.send(
                to=send_to,
                subject="Insurance Policy Summary Report – Attached PDF",
                contents=email_body,
                attachments=[pdf_name]
            )
            print(f"[INFO] Email sent → {send_to}")
        except Exception as e:
            print("[ERROR] Email failed:", e)
    else:
        print("\n[INFO] Email sending skipped. PDF saved only.")

    print("\n====================================================")
    print("  TASK COMPLETED – PDF GENERATED")
    print("====================================================\n")


if __name__ == "__main__":
    main()
